#!/usr/bin/with-contenv sh

set -euo pipefail
export BF_E=`basename ${0}`


#======================================================================================================================
# Restart the aspnet service.
#======================================================================================================================

bf-debug "Restarting application."
bf-svc restart aspnet
