#!/usr/bin/with-contenv sh

set -euo pipefail
export BCG_E=`basename ${0}`


#======================================================================================================================
# Restart the aspnet service.
#======================================================================================================================

bcg-debug "Restarting application."
bcg-svc restart aspnet
