#!/usr/bin/with-contenv sh

set -euo pipefail
export BCG_E=`basename ${0}`


#======================================================================================================================
# Check arguments.
#======================================================================================================================

[[ -z "${1-}" ]] && bcg-error "You must provide the app operating directory."


#======================================================================================================================
# Verify ASPNET_ASSEMBLY is set.
#======================================================================================================================

[[ -z "${ASPNET_ASSEMBLY}" ]] && bcg-error "ASPNET_ASSEMBLY environment variable must be set."


#======================================================================================================================
# Verify assembly exists before running it.
#======================================================================================================================

bcg-env ASPNET_SLEEP 0
ASSEMBLY_PATH=${1}/${ASPNET_ASSEMBLY}
if [ -f ${ASSEMBLY_PATH} ] ; then

    bcg-echo "Starting ASP.NET application."
    bcg-debug "${ASSEMBLY_PATH}."

    s6-setuidgid www /usr/bin/dotnet ${ASSEMBLY_PATH}

else

    bcg-notok "${ASSEMBLY_PATH} not found."
    bcg-env ASPNET_SLEEP 30

fi
