#!/usr/bin/with-contenv sh

set -euo pipefail
export BCG_E=`basename ${0}`


#======================================================================================================================
# Set permissions of published code.
#======================================================================================================================

bcg-ch -o www:www -m 0400 -t f ${ASPNET_APP_PUBLISH}
bcg-ch -o www:www -m 0500 -t d ${ASPNET_APP_PUBLISH}


#======================================================================================================================
# Stop application.
#======================================================================================================================

aspnet-stop


#======================================================================================================================
# Switch code from staging to live.
#======================================================================================================================

bcg-echo "Switching code..."

TEMP=$(mktemp -d src.XXXXXX) || bcg-error "Unable to create temporary source directory."

bcg-debug " .. moving live files to ${TEMP}"
mv ${ASPNET_APP_LIVE}/* ${TEMP}

bcg-debug " .. moving staging files to ${ASPNET_APP_LIVE}"
mv ${ASPNET_APP_PUBLISH}/* ${ASPNET_APP_LIVE}

bcg-debug " .. moving live files to ${ASPNET_APP_PUBLISH}"
mv ${TEMP}/* ${ASPNET_APP_PUBLISH}

bcg-done


#======================================================================================================================
# Start application.
#======================================================================================================================

aspnet-start
