#!/bin/sh

set -euo pipefail
export BF_E=`basename ${0}`


#======================================================================================================================
# Add www user.
#======================================================================================================================

bf-adduser www


#======================================================================================================================
# Install dotnet dependencies.
#======================================================================================================================

apk add --no-cache \
    ca-certificates \
    icu \
    krb5-libs \
    libgcc \
    libintl \
    libssl1.1 \
    libstdc++ \
    zlib


#======================================================================================================================
# Ensure target platform is set.
#======================================================================================================================

[[ -z "${TARGETPLATFORM-}" ]] && bf-error "Target platform not set."


#======================================================================================================================
# Get target platform architecture.
#======================================================================================================================

case "${TARGETPLATFORM}" in

    linux/amd64)
        ARCH="x64"
        ;;

    linux/arm64)
        ARCH="arm64"
        ;;

    *)
        bf-error "Unsupported target platform: ${TARGETPLATFORM}."
        ;;

esac

bf-echo "Platform architecture ${ARCH}."


#======================================================================================================================
# Get .NET Version.
#======================================================================================================================

cd /tmp

V=$(cat DOTNET_REVISION)
bf-echo ".NET version ${V}."


#======================================================================================================================
# Verify checksum of a dotnet download.
#   1   Either 'runtime' or 'aspnet'
#======================================================================================================================

verify () {

    DL="${ASPNET_VERSION_MINOR}-${ARCH}-${1}"

    case "${DL}" in

        3.1-x64-runtime)    HASH="a005ac073face06883172dca52a3b4cb94a60213533ad9ec4889b27c9588eeb397014af346d27bbbeae015907550d7cfa0f402c995594bc73f2bc45279e56adc" ;;
        3.1-arm64-runtime)  HASH="fbd103c901d44065d9a1ec3383baf2253e3df2c1ccc774b13793b5affc3d058da649cd080a12a377bad8bdc212effe973dff4a1414980e00de32cfd54363a46c" ;;
        6.0-x64-runtime)    HASH="e3eb4804dddbc34be37e3d984c13a668605ef7eea6b2daca95ea3fa7ca51b2fe4845df1ad0d343de9075796bf0d4474d7e14e5b3b4b515005d0e24ec53237ad3" ;;
        6.0-arm64-runtime)  HASH="3f5ca6d2e498e11bf1b46cf9ba456a4788a4dcb7ba4b0e52301bb9a3e2d511a8a9bd173be0cc8639c0297d90ad911a259da53ac2f6fd066313d79025ca42a5ef" ;;
        7.0-x64-runtime)    HASH="21cf30a3d3f30945d8b1f4b4d7462bdc589602f29258dc40823c5ea33e09a90a149821839b5d3df6e9dae4e898de404fd4a90f44d86ff5921362cef298b9c358" ;;
        7.0-arm64-runtime)  HASH="4919b4bed55ba8c2e7025c2ce2b1c9424efaa323152b3ad7edba18d5ac1419149badfe5da228678205419e82ed42587469cad5c81b06dbbd0198bca56cb84151" ;;

        3.1-x64-aspnet)     HASH="d7b4bb21592338ea9c6f3441a01ca538799fcfa047670923100545f8e6c3c6fa9cc11dcea6c130c871146ab1875853a2ccee78ed4e907ca897adfeb9241eaaa8" ;;
        3.1-arm64-aspnet)   HASH="36889945d974d440dc55e6631a61b19f6a6b6b6513cbd92f44ecdcda05e1215c61b6b2ae5ab0d1e74d8c7bbe5418f76c6dae81cbd53581f00fa02a6394aeebf6" ;;
        6.0-x64-aspnet)     HASH="eb8013608488e7a15dfa847229b7a3d0771312bcf63ddd099846c0ceaf7b506b8a2acb41de40affc8e72adb0526d5c6daf0a059e19e73436f4b3bdc258e153a4" ;;
        6.0-arm64-aspnet)   HASH="55945e23e2f4140af61f785a47ee15ec94880d52683e1881fb184b2341a1ecf8e04650e1fd896dd44d9493fe0fd3a9365f10dadb897560f42f1bc4cf5b7b9924" ;;
        7.0-x64-aspnet)     HASH="a1d2ef3859702663ba4786898f3bea1e5c62e54a3628891adfcadaec53b070de2f5af631379db1173ded257009fdd23a673ec69e36d519fe9577760f8a2b547b" ;;
        7.0-arm64-aspnet)   HASH="e43f4647b784954fa3a06c4ef38f73eb56cb46e71bbf53bff4e59e1f0f805ce480364a8bf340ae6a1a0a6c887968d5a9058c9a90c0f93795d74cf9f65393736e" ;;

        *)                  bf-error "Unsupported dotnet download: ${DL}." ;;

    esac

    bf-echo "Verifying ${1} download..."
    echo "${HASH}  ${1}.tar.gz" | sha512sum -c -
    bf-done

}


#======================================================================================================================
# Download and install .NET Runtime.
#======================================================================================================================

DOTNET=/usr/share/dotnet

if [ "$(echo ${V} | cut -c 1)" == "7" ] ; then
    V="7.0.0-rc.1.22426.10"
    bf-echo "Changing version to ${V}."
fi

RUNTIME="runtime"
RUNTIME_URL="https://dotnetcli.azureedge.net/dotnet/Runtime/${V}/dotnet-runtime-${V}-linux-musl-${ARCH}.tar.gz"
bf-echo "Downloading ${RUNTIME_URL}..."
wget -O ${RUNTIME}.tar.gz ${RUNTIME_URL}
bf-done

verify ${RUNTIME}

bf-echo "Installing .NET runtime..."
mkdir -p ${DOTNET} \
    && tar -C ${DOTNET} -oxzf ${RUNTIME}.tar.gz \
    && ln -s ${DOTNET}/dotnet /usr/bin/dotnet

[[ -d ${DOTNET} ]] && bf-done \
    || bf-error ".NET runtime not installed."


#======================================================================================================================
# Download and install ASP.NET Runtime.
#======================================================================================================================

if [ "$(echo ${V} | cut -c 1)" == "7" ] ; then
    V="7.0.0-rc.1.22427.2"
    bf-echo "Changing version to ${V}."
fi

ASPNET="aspnet"
ASPNET_URL="https://dotnetcli.azureedge.net/dotnet/aspnetcore/Runtime/${V}/aspnetcore-runtime-${V}-linux-musl-${ARCH}.tar.gz"
bf-echo "Downloading ${ASPNET_URL}..."
wget -O ${ASPNET}.tar.gz ${ASPNET_URL}
bf-done

verify ${ASPNET}

bf-echo "Installing ASP.NET..."
tar -ozxf ${ASPNET}.tar.gz -C ${DOTNET} ./shared/Microsoft.AspNetCore.App

[[ -d ${DOTNET}/shared/Microsoft.AspNetCore.App/${V} ]] && bf-done \
    || bf-error "ASP.NET runtime not installed."
