FROM bcgdesign/alpine-s6:auto

ARG TARGETPLATFORM="linux/amd64"

EXPOSE 5000

ENV \
    # Must be defined so the service can run the application
    ASPNET_ASSEMBLY= \
    # Configure web servers to bind to port 5000
    ASPNETCORE_URLS="http://+:5000" \
    # Otherwise it is set incorrectly to the S6 service directory
    ASPNETCORE_CONTENTROOT="/app/live" \
    # Enable detection of running in a container
    DOTNET_RUNNING_IN_CONTAINER=true \
    # Set the invariant mode since icu_libs isn't included (see https://github.com/dotnet/announcements/issues/20)
    DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=true

COPY ./overlay /
COPY ./5.0/DOTNET_REVISION /tmp/VERSION

RUN bf-install

VOLUME [ "/app/live", "/app/publish" ]
