#!/bin/bash

#======================================================================================================================
# Download and run installer
#======================================================================================================================

cd /tmp

INSTALLER="dotnet-install.sh"
URL="https://dot.net/v1/${INSTALLER}"
echo " - downloading ${URL}..."
curl -sL -o ${INSTALLER} ${URL} && chmod +x ${INSTALLER}
echo " - done."

echo " - installing ASP.NET v${DOTNET_VERSION}..."
./${INSTALLER} --architecture amd64 --version ${DOTNET_VERSION} --runtime aspnetcore

PROCESS_PATH=`cat /root/.dotnet`
echo "PROCESS_PATH: ${PROCESS_PATH}"
ls /root/.dotnet

INSTALLED_VERSION=`dotnet --version`
if [ "${INSTALLED_VERSION}" == "${DOTNET_VERSION}" ] ; then
    echo " - done."
    exit 0
else
    echo " - error."
    exit 1
fi
