#!/command/with-contenv sh

set -euo pipefail
export BF_E=`basename ${0}`


#======================================================================================================================
# Add environment variables.
#======================================================================================================================

# Library configuration
bf-env "ASPNET_LIB" "${BF_LIB}/aspnet"

# app directories
ASPNET_APP=/app
bf-env "ASPNET_APP" "${ASPNET_APP}"
bf-env "ASPNET_APP_LIVE" "${ASPNET_APP}/live"
bf-env "ASPNET_APP_PUBLISH" "${ASPNET_APP}/publish"
