#!/usr/bin/with-contenv sh

set -euo pipefail
export BCG_E=`basename ${0}`


#======================================================================================================================
# Add environment variables.
#======================================================================================================================

# Library configuration
bcg-env "ASPNET_LIB" "${BCG_LIB}/aspnet"

# app directories
ASPNET_APP=/app
bcg-env "ASPNET_APP" "${ASPNET_APP}"
bcg-env "ASPNET_APP_LIVE" "${ASPNET_APP}/live"
bcg-env "ASPNET_APP_STAGING" "${ASPNET_APP}/staging"
