#!/usr/bin/with-contenv sh

set -euo pipefail


#======================================================================================================================
# If an FTP password is set, create the ftp user and check for the SSL certificate
#======================================================================================================================

if [ ! -z "${FTP_PASSWORD}" ] ; then

    _echo "Adding ftp user..."

    htpasswd -cd /etc/vsftpd/vsftpd.passwd ftps
    htpasswd -c -p -b /etc/vsftpd/vsftpd.passwd ftps $(openssl passwd -1 -noverify ${FTP_PASSWORD})



    _done

    SSL=/etc/ssl
    CRT=${SSL}/crt.pem
    KEY=${SSL}/key.pem

    _echo "Generating SSL certificate and key..."
    if [ -f ${CRT} ] ; then
        _ok "Certificate already exists."
        exit 0
    fi

    openssl req -newkey rsa:2048 \
        -x509 \
        -sha256 \
        -days 3650 \
        -nodes \
        -out ${CRT} \
        -keyout ${KEY} \
        -subj "/C=NA/ST=NA/L=NA/O=NA/OU=NA/CN=NA"
    _done

fi
