#!/usr/bin/with-contenv sh

set -euo pipefail
export BF_E=`basename ${0}`


#======================================================================================================================
# Output .NET Version.
#======================================================================================================================

VERSION=\
    # get list of installed runtimes
    `dotnet --list-runtimes \
    # get the line with the versio non
    | grep "Microsoft.NETCore.App" \
    # strip out everything except numbers and full stops
    | sed 's/[^0-9\.]*//g' \
    # trim full stops from start of string
    | sed 's/^\.*//g' \
    # trim full stops from end of string
    | sed 's/\.*$//g'

# output nicely
bf-echo ".NET ${VERSION} installed."
