#!/usr/bin/with-contenv sh

set -euo pipefail
export BF_E=`basename ${0}`


#======================================================================================================================
# Output .NET Version.
#======================================================================================================================

# get version from list of installed runtimes
VERSION=`dotnet --list-runtimes \
    | grep "Microsoft.NETCore.App" \
    | sed 's/[^0-9\.]*//g' \
    | sed 's/^\.*//g' \
    | sed 's/\.*$//g' \
    | xargs`

# output nicely
bf-echo ".NET ${VERSION} installed."
