#!/usr/bin/with-contenv sh

set -euo pipefail
export BF_E=`basename ${0}`


#======================================================================================================================
# Output .NET Version.
#======================================================================================================================

VERSION=`dotnet --info | grep "Version" | xargs | tr "Version: " " "`
bf-echo ".NET ${VERSION} installed."
