#!/usr/bin/with-contenv sh

set -euo pipefail


#======================================================================================================================
# Terminate the container if we haven't just been asleep.
#======================================================================================================================

if [ -z "${ASPNET_SLEEP-}" || "${ASPNET_SLEEP}" = "0" ] ; then
    bcg-svc-finish -s ${PWD##*/} -t
else
    bcg-svc-finish -s ${PWD##*/}
fi
