#!/usr/bin/with-contenv sh

set -euo pipefail


#======================================================================================================================
# Stop the dotnet service.
#======================================================================================================================

bcg-echo "Stopping dotnet service..."
SVC=/var/run/s6/services/dotnet
s6-svc -t ${SVC}
bcg-done
