#!/usr/bin/with-contenv sh

set -euo pipefail


#======================================================================================================================
# Run /usr/local/bin/dotnet-run executable
#======================================================================================================================

_echo "Starting ASP.NET application"
s6-setuidgid www dotnet-run
