#!/command/with-contenv sh

set -euo pipefail
export BF_E=`basename ${0}`


#======================================================================================================================
# Stop the aspnet service.
#======================================================================================================================

s6-rc -d change aspnet
kill $(ps aux | grep ${ASPNET_ASSEMBLY} | grep -v 'grep' | awk '{print $1}')
