#!/command/with-contenv sh

set -euo pipefail
export BF_E=`basename ${0}`


#======================================================================================================================
# Restart the aspnet service.
#======================================================================================================================

bf-echo "Restarting application."
bf-svc restart aspnet
