#!/command/with-contenv sh

set -euo pipefail
export BF_E=`basename ${0}`


#======================================================================================================================
# Restart the aspnet service.
#======================================================================================================================

${ASPNET_LIB}/disable

bf-echo "Restarting ASP.NET application."
s6-rc -u change aspnet
