#!/command/with-contenv sh

set -euo pipefail


#======================================================================================================================
# Check for published files.
#======================================================================================================================

[[ -z "$(ls -A ${ASPNET_APP_PUBLISH})" ]] && bf-error "Please publish source files first." "aspnet/switch"


#======================================================================================================================
# Disable application (so it won't try to restart before we're ready).
#======================================================================================================================

${ASPNET_LIB}/disable


#======================================================================================================================
# Switch code from publish to live.
#======================================================================================================================

bf-echo "Switching code..." "aspnet/switch"

TEMP=$(mktemp -d src.XXXXXX) || bf-error "Unable to create temporary source directory." "aspnet/switch"

if [ "$(ls -A ${ASPNET_APP_LIVE})" ] ; then
    bf-debug " .. moving live files to ${TEMP}" "aspnet/switch"
    mv ${ASPNET_APP_LIVE}/* ${TEMP}
fi

bf-debug " .. moving published files to ${ASPNET_APP_LIVE}" "aspnet/switch"
mv ${ASPNET_APP_PUBLISH}/* ${ASPNET_APP_LIVE}

if [ "$(ls -A ${TEMP})" ] ; then
    bf-debug " .. moving live files to ${ASPNET_APP_PUBLISH}" "aspnet/switch"
    mv ${TEMP}/* ${ASPNET_APP_PUBLISH}
fi

bf-debug " .. reapplying permissions" "aspnet/switch"
bf-ch-apply "${BF_CH_D}/10-aspnet"

bf-done "aspnet/switch"
